name: .NET Code Formatting

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  dotnet-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Add dotnet-format problem matcher
      uses: xt0rted/dotnet-format-problem-matcher@master

    - name: Restore dotnet tools
      uses: xt0rted/dotnet-tool-restore@master

    - name: Run dotnet format
      uses: xt0rted/dotnet-format@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        version: 'latest'
        action: 'check'
        only-changed-files: 'true'
