name: Check Code Formatting

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Install dotnet-format
      run: dotnet tool install -g dotnet-format --version 5.0.211103.1

    - name: Run dotnet-format
      run: dotnet format --check --workspace ExampleOrder.sln
